### ISSUE TITLE
requirements.txt needed

### ISSUE THREAD

**Issue by radio24** [Nonie689/exclude-slow-tor-relays-ng#1]
**Describe the bug**
When I try to start the program, I get the following error:
```
Traceback (most recent call last):
  File "/home/torbox/torbox/./exclude-slow-tor-relays-ng", line 242, in <module>
    main(_get_args())
  File "/home/torbox/torbox/./exclude-slow-tor-relays-ng", line 200, in main
    log.setLevel(logging._levelNames[args.loglevel])
AttributeError: module 'logging' has no attribute '_levelNames'
```

**To Reproduce**
OS: Raspbian OS (aarch64 GNU/Linux) with kernel version 5.15.32-v8+
Shell: GNU bash, version 5.1.4(1)
Python version: 3.9.2

**Additional context**
I guess the program needs a specific Python module, which is missing from my system. The file "requirements.txt" help users install the required Python modules in the correct version.

**Comment by Nonie689** [comment]
hey, I haven't released, its broken yet.

have this only cloned, from the creator, cause I want to create a new version & fix this problem. 

The initial creator hasn't a requirement.... so I has, had the same problem!!

I going to work this = ~  in 2 month

 --

**Comment by Nonie689** [comment]
Could someone test my project [ firevigeo-torloader?? at: https://github.com/Nonie689/firevigeo-torloader ]

and could someone create an gif video for this project??

To check, that we should insert this in TorBox Project, on the v5.2/v5.3 release ??

with this testing conditions:

    Speed Test without enabled.
    Speed Test with tor enabled
    Speed Test with firefideo-load balanced [ firevigeo.sh -s (No extra parameters) ]

with these Online Speedtester URL's:

    - https://myspeedcheck.net/speedtest/google-fiber
           - My results Down: 80mbps [1. No Tor, 4mbps [2. single Tor] , 45 mbps [3. firevigeo-torloader [ firevigeo.sh -s (No extra parameters)
    - https://fiber.google.com/intl/es/speedtest/
         - My results - Down: 90mbps [1. No Tor], 3mbps [2. single Tor], 50mbps [3. firevigeo-torloader [ firevigeo.sh -s (No extra parameters)
    - https://speedtest.googlefiber.net/
        - Not able to check, cause of, 503] - [No response]

My arranged ISP - Provider Speed max Download, - 100mbps [ with vDSL ]

so the 80/90mbps - really comming in!

I hope someone could try it with ISP arranged max Download speed greater than 1000mbps!!

**Comment by Nonie689** [comment]
I have rewrite it!

It should now work!

**Comment by radio24** [comment]
Thanks, I will try it, soon
